### ISSUE TITLE
Socketing to Hands when grabbed

### ISSUE THREAD

**Issue by CoryBrown-42** [Mountwest-Gaming/VR-Classroom#12]
hand socket

**Comment by NightPotato** [comment]
@CoryBrown-42 What are the weapons going to be used for in the game? Me and Seth have no idea other than to hurt the enemy but isn't that the point of the flashlight also?

**Comment by NightPotato** [comment]
Can we push this back for after Expo as we didn’t plan the weapons out besides the flashlight?

**Comment by CoryBrown-42** [comment]
Coming back to this soon as weapons.
