### ISSUE TITLE
Set Bounds for Player Teleporting

### ISSUE THREAD

**Issue by NightPotato** [Mountwest-Gaming/VR-Classroom#15]
We need to limit the way the player can teleport so the player will not pass into the objects placed around the room.

**Comment by theRealDarkFact** [comment]
Is there not a way to look at the zone to be teleported to and select an area not occupied?

**Comment by NightPotato** [comment]
Right now it lets you teleport anywhere you point. Cory and I were talking about making a system to ignore stuff under objects you shouldn't be able to teleport into.

**Comment by theRealDarkFact** [comment]
Ah, i see

**Comment by NightPotato** [comment]
This should be fixed as latest master introduce a fix for the navmesh was added in the second floor level design.

**Comment by CoryBrown-42** [comment]
This will need to be updated to include the "ability" to pass through walls.
