### ISSUE TITLE
HTC Vive - Standing Only - Player Height to Room Scale

### ISSUE THREAD

**Issue by NightPotato** [Mountwest-Gaming/VR-Classroom#18]
When using stand only for the HTC Vive, the play area is very small compared to the player. Could use an additional person setting up Standing Mode for the Vive before tagging an issue as a bug. However, tables are still very low compared to players for both Vive and Oculus Rift.

**Comment by theRealDarkFact** [comment]
I can help at school with the vr height I'm a shorter person so that should cover the low end

**Comment by CoryBrown-42** [comment]
We'll put this on the back burner as far as TODO but we'll remember it when we go to set up before the expo.

**Comment by CoryBrown-42** [comment]
I'm going to be working on this from home and I'll possibly be purchasing assets and refining some of these kind of issues.
