### ISSUE TITLE
Enemy Reaction to flashlight

### ISSUE THREAD

**Issue by CoryBrown-42** [Mountwest-Gaming/VR-Classroom#4]
Repeat the wall and player trace

**Comment by NightPotato** [comment]
I have started support for picking up the flashlight just need the model. See https://github.com/Mountwest-Gaming/VR-Classroom/projects/7#card-27630666

**Comment by CoryBrown-42** [comment]
Also if that's the enemy that's going to be in the game @SirSethington then can you continue working on it. It is a good start but it needs some serious work.
