### ISSUE TITLE
Flashlight

### ISSUE THREAD

**Issue by CoryBrown-42** [Mountwest-Gaming/VR-Classroom#6]
3D model needed

**Comment by theRealDarkFact** [comment]
I have a completed flashlight with a light source I am allowed to upload it.

**Comment by CoryBrown-42** [comment]
Once the model is in game we'll close the issue and make one for the programming of the AI avoidance of the flashlight

**Comment by CoryBrown-42** [comment]
Gave it to jefferey to texture

**Comment by CoryBrown-42** [comment]
is this in the game yet
