### ISSUE TITLE
Decide on player health / Sanity meter

### ISSUE THREAD

**Issue by CoryBrown-42** [Mountwest-Gaming/VR-Classroom#8]

**Comment by guthrie5** [comment]
Depending on capabilities and user comfort, a sanity meter would be really nice. You could have visuals change with a lack of sanity and sounds and music changes.

**Comment by NightPotato** [comment]
Both visual and sound are a good idea and I will start implementing the basics into the player soon.

**Comment by CoryBrown-42** [comment]
See design doc
